# ---------------- Developed by Adnan Ajmal - Next.js CI ---------------- #
# This workflow is a Continuous Integration (CI) pipeline for a Next.js application.
# It installs dependencies and builds the Next.js application without deploying it to a server.
# Make sure to customize it according to your application's specific needs.

name: 'Next.js CI'

env:
  APP_NAME: ${{ vars.APP_NAME }}
  COMPONENT_NAME: ${{ vars.COMPONENT_NAME }}
  NODE_ENV: ${{ github.event_name == 'push' && 'dev' || github.event.inputs.environment }}

on:
  push:
    branches:
      - child
  pull_request:
    branches:
      - child

jobs:
  ci:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js with version 18.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # Step 3: Install dependencies.
      - name: Install dependencies
        run: |
          yarn install

      # Step 4: Run linting to ensure code quality.
      - name: Run Lint
        run: |
          yarn lint

      # Step 6: Build the Next.js project.
      - name: Build project
        run: |
          yarn build
