# ---------------- Developed by MERN TL ---------------- #
# This workflow is a Continuous Integration (CI) pipeline for testing a Next.js application.
name: "CI"

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted # Set this to 'ubuntu-latest' if you're not hosting your repo on falcon

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Updated to Node.js 18

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check # Add this script to your package.json if using TypeScript

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test # Add this if you have tests set up
